var express = require('express')
  , session = require('express-session')
  , passport = require('passport')
  , io = require('socket.io')
  , app = express()
  , redisClient = require('redis').createClient()
  , server = require('http').createServer(app)
  , sessionStore = new session.MemoryStore()
  , passMan = require('./passportManager')(passport)
  , appMan = require('./applicationManager')(app, passport, session, sessionStore)
  , sockMan = require('./socketioManager')(io, server, passport, sessionStore)
  , router = require('./routes')(express, app, passport)

server.listen(3001, function() {
  console.log('Server listening on port 3001')
})